name: build-and-push

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: "Docker Hub Deployment"
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short commit sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (main branch)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            stargazer2026/wiim-now-playing:latest
            stargazer2026/wiim-now-playing:sha-${{ env.SHORT_SHA }}

      - name: Build and push (dev branch)
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            stargazer2026/wiim-now-playing-dev:latest
            stargazer2026/wiim-now-playing-dev:sha-${{ env.SHORT_SHA }}

      - name: Build and push (version tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            stargazer2026/wiim-now-playing:${{ github.ref_name }}
            stargazer2026/wiim-now-playing:latest
            stargazer2026/wiim-now-playing:sha-${{ env.SHORT_SHA }}
